# Generated by Django 5.1.7 on 2025-04-14 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_uid', models.CharField(max_length=100, unique=True, verbose_name='주문번호')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='결제 금액')),
                ('status', models.CharField(choices=[('ready', '결제 대기'), ('paid', '결제 완료'), ('cancelled', '결제 취소'), ('failed', '결제 실패')], default='ready', max_length=20, verbose_name='결제 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('imp_uid', models.CharField(blank=True, max_length=100, null=True, verbose_name='아임포트 거래 고유번호')),
                ('cart_items', models.ManyToManyField(related_name='payments', to='enrollments.cartitem', verbose_name='장바구니 항목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
